### ISSUE TITLE
Cannot Find TimeSeries

### ISSUE THREAD

**Issue by divyesh2506** [QuantSoftware/QuantSoftwareToolkit#73]
```Traceback (most recent call last):
  File "Validation.py", line 123, in <module>
    import QSTK.qstkutil.tsutil as tsu
  File "/usr/local/lib/python2.7/dist-packages/QSTK-0.2.8-py2.7.egg/QSTK/qstkutil/tsutil.py", line 19, in <module>
    from QSTK.qstkutil import qsdateutil
  File "/usr/local/lib/python2.7/dist-packages/QSTK-0.2.8-py2.7.egg/QSTK/qstkutil/qsdateutil.py", line 38, in <module>
    GTS_DATES = _cache_dates()
  File "/usr/local/lib/python2.7/dist-packages/QSTK-0.2.8-py2.7.egg/QSTK/qstkutil/qsdateutil.py", line 36, in _cache_dates
    return pd.TimeSeries(index=dates, data=dates)
AttributeError: 'module' object has no attribute 'TimeSeries'

Any Ideas on how to solve this?

**Comment by Eimert** [comment]
Fix is described in [this pull request](https://github.com/QuantSoftware/QuantSoftwareToolkit/pull/65).

**Comment by parrajeremy** [comment]
Take a look at the version of Pandas you are using (i.e. run python Validation.py from Examples). Most likely you have too new a version; need to roll it back to (0.7.3). $pip install pandas==0.7.3

**Comment by schneiderfelipe** [comment]
As cited [here](https://stackoverflow.com/questions/44991254/attributeerror-module-object-has-no-attribute-timeseries-after-python-valid#comment77002689_44991254), a workaround might be:

    import pandas as pd
    pd.TimeSeries = pd.Series
